# Generated by Django 5.1 on 2024-08-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=100),
        ),
    ]
